### ISSUE TITLE
Ionic 5.4.15

### ISSUE THREAD

**Issue by mrmaarek** [ZebraDevs/DataWedge-Ionic-Demo#14]
if you would like to see a version of this application that compiles with Ionic v4 & v5 and uses WebIntent then please see the 'Transition_To_WebIntent' branch.

Well i've actually checked out the branch and im running npm install into the directory. 
There are so many warnings and deprecated packages in it. I can't even do a npm install:

NPM -v = 6.10.3
NODE -v = 12.10.0.

6835 verbose stack Error: node-sass@4.7.2 postinstall: `node scripts/build.js`

`npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

When i just startup a clean ionic helloworl it just works.

**Comment by kulkarniswapnil** [comment]
Any resolution to it. I am facing the same issue.

**Comment by darryncampbell** [comment]
```
cordova -v
> 9.0.0 (cordova-lib@9.0.1)
```
```
ionic -v 
> 6.0.0
```

```
node -v
> v10.16.3
```
```
npm -v
> 6.13.7
```
```
git clone https://github.com/Zebra/ZebraIonicDemo.git
cd DataWedge-Ionic-Demo
git checkout Transition_To_WebIntent
npm install
Connect Zebra device to adb
ionic cordova run android --device
```

The above steps seem to successfully build and run the application on my TC52.  Am I missing something?

**Comment by kulkarniswapnil** [comment]
Thank you for reply 

I have checked mine and I have following versions. I have done steps extactly as provided.

cordova -v 9.0.0 (cordova-lib@9.0.1)
ionic -v 6.4.0
node -v v12.14.0
npm -v 6.13.4

Is anything to do with node-sass ?  I have 4.13 installed

**Comment by darryncampbell** [comment]
I'm not sure if I had it installed before but I just installed it and have 4.1.3

```
node-sass -v
>node-sass       4.13.1  (Wrapper)       [JavaScript]
>libsass         3.5.4   (Sass Compiler) [C/C++]
```

I tried again with a clean clone after installing node-sass and it still builds OK for me but there is lots of output and it even starts building c++ code at one point.  I have Visual Studio installed so it seems OK with that.  I'm obviously on Windows.  

Maybe the solution is to try again from a hello world project and slowly add in the bits for DataWedge integration (Web-Intent, cordova-plugin-intent) like the original poster did... I suspect the issue is with my setup but I haven't touched Ionic development in a long time I'm afraid.

**Comment by kulkarniswapnil** [comment]
Thanks for the reply. Will go through the process. May I know that is this supports Capacitor. It's very important to know.

**Comment by darryncampbell** [comment]
>May I know that is this supports Capacitor with react. It's very important to know.

I have no experience with Capacitor I'm afraid.  The [documentation](https://capacitor.ionicframework.com/docs/cordova/using-cordova-plugins/) implies that it is possible to use Cordova plugins in a capacitor app but I have never tried it.

**Comment by JoJo-Bear** [comment]
I am having the same problem.
But it appears to be a problem related to the ageing of the used packages.
Even so, while looking for a solution I noticed it stil uses the ionic-angular package instead of the @ionic/anuglar. Which probably is cause some of the issues.

However the biggest issue, what you all have been noticing, is that it cannot be build with newer versions of node. In order to youse the provided demo you need to downgrade your node to  10.20.1 ( ive tried 14.3.1, 13.7.0 and 12. something, none of those worked).

So in order to use and build the demo in a fast way, just downgrade node.

**Comment by kulkarniswapnil** [comment]
Thanks for replying. I am using the Ionic 5 and Capacitor. I worked it out by not using web intent I used the **ionic cordova plugin add com-darryncampbell-cordova-plugin-intent** and it worked like a charm.  I created a demo it's not is good shape but scanning works as I wanted https://github.com/kulkarniswapnil/DataWedge-Ionic-Capacitor-React-Demo

**Comment by darryncampbell** [comment]
Finally got around to updating this project to Ionic 6 so the master branch should now work: https://github.com/ZebraDevs/DataWedge-Ionic-Demo/pull/16
